import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/component/Navbar";
import Footer from "@/component/Footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${inter.className} h-full antialiased `}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="container mx-auto">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
